### PR TITLE
chore: add bump:version script

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- update `1.0.0` version of package in `package.json`
- add `bump:version` script

### CODE REVIEW

**Comment by derberg** [comment]
I suggest `fix: ` otherwise release will not be triggered, and bump in `package.json` will not take place, and bump in projects that use this package will not take place

**Comment by magicmatatjahu** [comment]
@derberg which projects? I update version in `package-lock.json` manually,

**Review by imabp — APPROVED** [review]

**Comment by derberg** [comment]
> which projects?

sorry, I understood from past conversations that your requirement for `problem` to be completed is to use it in some project.

anyway, I guess you can merge then

**Comment by imabp** [comment]
@magicmatatjahu feel free to merge when you are ready

**Comment by magicmatatjahu** [comment]
@derberg 

> sorry, I understood from past conversations that your requirement for problem to be completed is to use it in some project.

Yeah, we tested that package but using transformed `lib` folder in the `server-api`.

**Pull request merged**
